accounts/urls.py
from django.urls import path
from .views import (
    user_create_view,
    user_login_view,
    user_logout_view,
    user_profile_view,
    retrive_user_name

)
app_name ='accounts'
urlpatterns = [
    path('create/', user_create_view, name = "create"),
    path('login/',user_login_view, name = "login"),
    path('logout/',user_logout_view,name ="logout"),
    path('<str:username>/',user_profile_view,name ="profile"),
    path('<str:username>/',retrive_user_name,name ="_profile_"),


]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('static_pages.urls', namespace = 'static_pages')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts'))

]

posts/urls.py
from django.urls import path, include
from .views import(
    post_create_view,
    post_detail_view,
    post_list_view,
    post_update_view,
    post_delete_view
)

app_name = 'posts'
urlpatterns = [
    path('create/',post_create_view,name= 'create'),
    path('detail/<int:id>',post_detail_view,name= 'detail'),
    path('list/',post_list_view,name= 'list'),
    path('update/<int:id>',post_update_view,name = 'update'),
    path('delete/<int:id>',post_delete_view,name= 'delete')
]

static_pages/urls.py
from django.urls import path

from .views import home_view

app_name = 'static_pages'

urlpatterns = [
    path('',home_view, name ='home' ),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.conf import settings


User = settings.AUTH_USER_MODEL

class Post(models.Model):
    title = models.CharField(max_length = 255, blank = True, null = True)
    content = models.TextField(blank = True, null = True)
    created = models.DateTimeField(auto_now_add = True,blank = True, null = True)
    update = models.DateTimeField(auto_now = True,blank = True, null = True)
    author = models.ForeignKey(User, on_delete = models.CASCADE, blank = True, null = True)
    #author

static_pages/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login,logout
from posts.models import Post
from django.contrib import messages #import messages

User = get_user_model()

global retrive_user_name
def retrive_user_name(username):
    user = User.objects.get(username = username)
    return user

# Create your views here.
def user_create_view(request):
    if request.method == "POST":
        context={}
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
            username = request.POST['username']
            email = request.POST['email']

            try:
                user1 = User.objects.get(username = username)
                context['error'] = "Username or email already exists! "
                return render(request, 'accounts/create.html', context = context)
            except User.DoesNotExist:
                try:
                    user2 = User.objects.get(email = email)
                    context['error'] = "Username or email already exists!"
                    return render(request,'accounts/create.html',context = context)
                except User.DoesNotExist:
                    user = User.objects.create_user(username = username, email = email, password = password1)
                    return redirect('posts:list')


        else:
            context['error'] = "Password and Confirm Password must match!"
            return render(request,'accounts/create.html',context = context)

    else:
        return render(request,'accounts/create.html')

def user_login_view(request):
    if request.method =="POST":
        context = {}
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        if user is not None:
            login(request,user)
            return redirect('posts:list')
            #return render(request,'posts/list', context = context)
        else:
            context['error'] = "Invalid Login"
            return render(request,'accounts/login.html',context = context)
    else:

        return render(request,'accounts/login.html')


def user_logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        return render(request, 'accounts/logout.html')
    else:
        return redirect('accounts:login')

def user_profile_view(request,username):
    user = User.objects.get(username = username)
    posts = Post.objects.filter(author = user)
    context = {'posts' : posts}
    return render(request,'accounts/profile.html', context = context)

def profile_navbar(request):
    user = retrive_user_name()
    return render(request,'templates/navbar.html',context =user )

posts/views.py
from django.shortcuts import render,redirect
from .models import Post

from django.contrib.auth.decorators import login_required
# Create post view
@login_required
def post_create_view(request):

    if request.method == "POST":
        context ={}

        title = request.POST['title']
        content = request.POST['content']

        if title and content:
            user = request.user
            post = Post.objects.create(title= title, content = content,author = user)
            return redirect('posts:detail', id = post.id)
        else:
            context['error'] = 'Your title and content cant be empty'
            return render(request,'posts/create.html', context = context)
    else:
        return render(request,'posts/create.html')

#to view  one specific blog post
def post_detail_view(request,id):
    post = Post.objects.filter(id = id).first()
    context = {'post': post}
    return render(request, 'posts/detail.html', context = context)

#this will be to view all our blog post
def post_list_view(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'posts/list.html', context = context)

#update one specific post
@login_required
def post_update_view(request,id):
    context ={}
    post = Post.objects.filter(id = id).first()
    context['post']=post
    if request.user == post.author:
        if request.method == "POST":


            title = request.POST['title']
            content = request.POST['content']

            if title and content:
                post.title = title
                post.content = content
                post.save()
                context['error'] = 'There has been no error. Your post has been updated successfully!'
                return render(request,'posts/update.html',context= context)
            else:
                context['error'] = 'Your title and content cant be empty'
                return render(request,'posts/update.html', context = context)
        else:
            return render(request,'posts/update.html', context = context)
    else:
        return redirect('posts:list')

#delete one specific post
@login_required
def post_delete_view(request,id):
    post = Post.objects.filter(id=id).first()
    if request.user == post.author:
        if request.method== "POST":
            post.delete()
            return redirect('posts:list')
        else:
            return render(request, 'posts/delete.html')
    else :
        return redirect('posts:list')

static_pages/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
    return render(request,'static_pages/home.html')

accounts/templates/accounts/create.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <h1 class ="display-4"> Sign Up</h1>
    <h4 class ="text-danger">{{error}}</h4>
  </div>
  <div class="row">
    <div class="col-12">
      <form method = "POST">
        {% csrf_token %}
            <div class="form-group">
              <label for="username">Username</label>
              <input type="text" Class="form-control" name= "username" required/>
            </div>
            <br>
            <div class="form-group">
              <label for="email">Email</label>
              <input type="text" Class="form-control" name= "email" required/>
            </div>
            <br>
            <div class="form-group">
              <label for="password1">Password</label>
              <input type="password" Class="form-control" name= "password1" required />
            </div>
            <br>
            <div class="form-group">
              <label for="password2">Confirm Password</label>
              <input type="password" Class="form-control" name= "password2" required />
            </div> <br/>
            <input type="submit" value="Sign Up" class="btn btn-md btn-primary"/>
      </form>

    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="display-4">Log In</h1>
      {%if success %}
        <h4 class = "text-success">{{success}}</h4>
        <a href="{% url 'posts:list'  %}">See blogs</a>

      {% else %}
        <h4 class= "text-danger">{{error}}</h4>
      {% endif %}
      </div>
    </div>
  <div class="row">
    <div class="col-12">
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" name="username" class="form-control"/>
        </div>
        <br>

        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" name="password" class="form-control"/>
        </div>
        <br>
        <input type="submit"  value="Log In" class="btn btn-md btn-primary">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <br><br>
    <center><h1 class ="display-4">You are now logged out Successfully!</h1></center>
    <br>
    <center><h5> Thank You for all your valuable Contirbutions (:) </h5></center>
  </div>
</div>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <h1 class="display-4">{{user}}'s blog</h1>
  </div>
  <div class="row">
    <div class="col-12">
      {% for p in posts %}
      <div class="row">
        <div class="col-12">
          <a href="{% url 'posts:detail' id=p.id %}">{{p.title}} | By-{{p.author}}</a>
          <br />
          <p>{{p.content|slice:"255"}}....  </p>
        </div>
      </div>
        <hr/>
      {% endfor %}

</div>
  </div>
</div>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}
{% block content %}
<style>
textarea {
  resize :none;
}
</style>
  <div class="container px-5">
        <div class="row">
          <h1 class="display-4"> Create a new post!</h1>
        </div>
        <div class="row">
          <h4 class=" text-danger">{{error}}</h4>
        </div>
        <div class="row">
          <div class="COL-12">
            <form method ='POST'>
                {% csrf_token %}
                <div class="form-group">
                  <label for="title">Post Title</label>
                  <input type="text" name="title" class = "form-control"/><br>
                </div>
                <div class="form-group">
                  <label for="content">Post content</label>
                  <textarea name="content" rows="8" class = "form-control" ></textarea>
                </div>
                <br>
                <input type="submit" value="Create" class = "btn btn-md btn-primary mr-2"/>
                <a href="{% url 'posts:list' %}" class="btn btn-md btn-danger">Cancel</a>
                </form>
      </div>
    </div>
  </div>
{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="text-center">
        <h1 class="display-4">Are you sure, you want to delete?</h1>
      </div>
      <br/>
    </div>
    </div>
    <div class="row">
      <div class="col-12">
        <form  method="post">
            {% csrf_token %}
            <div class="text-center">
              <input type="submit" value="Yes" class="btn btn-md btn-danger"/>
              <a href="{% url 'posts:list' %}" class="btn btn-md btn-primary">No</a>
            </div>
        </form>
      </div>

    </div>
</div>



{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      	<h1 class="display-4">{{post.title}} | Written by - {{post.author}}</h1>
        <br/>
        <p>Created: {{post.created}} | Updated: {{post.update}} </p>
    </div>
    </div>
  <div class="row">
    <div class="col-12">
      <p>{{post.content}}</p>
    </div>
  </div>

  {% if request.user == post.author %}
      <div class="row">
          <div class="col-12">
          <a href="{% url 'posts:update' id=post.id %}" class="btn btn-md btn-secondary">Edit</a>
          <a href="{% url 'posts:delete' id=post.id %}" class="btn btn-md btn-danger">Delete</a>
        </div>
      </div>
  {% endif %}
</div>

{% endblock content %}

posts/templates/posts/list.html
{% extends 'base.html' %}
{% block content %}
<div class="container px-5">
  <div class="row">
      <h1 class="display-4">The Blog</h1>
  </div>
  <div class="row">
    <div class="col-12">
      {% for p in posts %}
      {% if p.author != None %}
      {% if p.title != "ANURAG TEST POST" %}
      <div class="row">
        <div class="col-12">
          <a href="{% url 'posts:detail' id=p.id %}">{{p.title}} | By-{{p.author}}</a>
          <br />
          <p>{{p.content|slice:"255"}}....  </p>
        </div>
      </div>
        <hr/>
        {% endif %}
        {% endif %}
      {% endfor %}
    </div>
  </div>
</div>


{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block content %}
<div class="container px-5">
  <div class="row">
    <div class="col-12">
      <h1 class="display-4"> Update post</h1>
      <h4 class="text-danger">{{error}}</h4>
    </div>
</div>
    <div class="row">
      <div class="col-12">
        <form method ='POST'>
          {% csrf_token %}
          <div class="form-group">
            <label for="title">Post Title</label>
            <input type="text" name="title" value="{{post.title}}" class = "form-control"><br>
          </div>
          <div class="form-group">
            <label for="content">Post content</label>
            <textarea name="content" rows="8" class ="form-control" >{{post.content}}</textarea>
          </div>
          <br/>
          <input type="submit" value="Update" class = "btn btn-md btn-primary">
          <a href="{% url 'posts:detail' id=post.id %}" class="btn btn-md btn-danger">Cancel</a>
        </form>
      </div>

    </div>
</div>


{% endblock content %}

static_pages/templates/static_pages/home.html
{% extends 'base.html' %}
{% block content %}

<style>
.p2 {
  font-family: Arial, Helvetica, sans-serif;
}
</style>
<div class="p-3 mb-2 bg-light text-dark text-center">
  <h1 class="display-4">Welcome to Our blog! </h1><br>
<p class="p2">
  Welcome to our blog Website. Here you view the blogs of all the people who have posted thier writings.<br>
  You can either be a guest or a content writer.<br>
    if you == Visitor<br>
    {<br>
      reach_out_to = All blog Posts<br>
      (have fun reading the posts written by our registered blog writers)<br>
    }<br>
  else if you == Blog writer<br>
    {<br>
      reach_out_to = register<br>
      then<br>
      {<br>
        login()<br>
      }<br>
      create_post()<br>
    }<br>
  else<br>
  {<br>
    Thank you for reaching out on this website<br>
  }<br>
  </p>
</div>


{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Our Blog</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  </head>
  <body>
    {%include 'navbar.html'%}
    {% block content %}
    {% endblock content %}
    {%include 'footer.html'%}
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

templates/footer.html
<!DOCTYPE html>
<html>

<head>
  <style media="screen">

  .footer-basic {
    padding:40px 0;
    background-color:#ffffff;
    color:#4b4c4d;

}

  .footer-basic ul {
    padding:0;
    list-style:none;
    text-align:center;
    font-size:18px;
    line-height:1.6;
    margin-bottom:0;
  }

  .footer-basic li {
    padding:0 10px;
  }

  .footer-basic ul a {
    color:inherit;
    text-decoration:none;
    opacity:0.8;
  }

  .footer-basic ul a:hover {
    opacity:1;
  }

  .footer-basic .social {
    text-align:center;
    padding-bottom:25px;
  }

  .footer-basic .social > a {
    font-size:24px;
    width:40px;
    height:40px;
    line-height:40px;
    display:inline-block;
    text-align:center;
    border-radius:50%;
    border:1px solid #ccc;
    margin:0 8px;
    color:inherit;
    opacity:0.75;
  }

  .footer-basic .social > a:hover {
    opacity:0.9;
  }

  .footer-basic .copyright {
    margin-top:15px;
    text-align:center;
    font-size:13px;
    color:#aaa;
    margin-bottom:0;
  }

  /* Credit to https://epicbootstrap.com/snippets/footer-basic */
  </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Untitled</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
</head>

<body>
  <div class = "footer">
    <div class="footer-basic">
        <footer>
            <div class="social"><a href="http://www.linkedin.com/in/anurag-swarup"><i class="icon ion-social-linkedin"></i></a>
              <a href="https://www.snapchat.com/add/a_swarup"><i class="icon ion-social-snapchat"></i></a>
              <a href="https://www.facebook.com/anurag.swarup/"><i class="icon ion-social-facebook"></i></a></div>
             <ul class="list-inline">
               <H7 class="copyright"> Brought to you by @Anurag_Swarup </h7>
               <p class="copyright">OuR FiRsT DrAfT © 2021   </p>

               <!-- <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li> -->
            </ul>

        </footer>
    </div>
  </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'static_pages:home'%}">OuR FiRsT DrAfT</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{%url 'posts:list' %}">All blog posts</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:create' %}">Create blog</a>
        </li>

        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}" >logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:8000/accounts/{{user}}" >my profile</a>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:create' %}">Signup</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href = "{% url 'accounts:login' %}" >Login</a>
              </li>
        {% endif %}
      </ul>
    </div>
</nav>